// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package listing

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Wire(db *gorm.DB) *Handler {
	listingRepository := ProvideRepository(db)
	listingService := ProvideService(listingRepository)
	listingHandler := ProvideHandler(listingService)
	return listingHandler
}
