// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Wire(db *gorm.DB) *Handler {
	userRepository := provideRepository(db)
	userService := provideService(userRepository)
	userHandler := provideHandler(userService)
	return userHandler
}
